config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #, controllers: { sessions: 'users/sessions' }

  resources :articles do
	  resources :comments
	end

	resources :payments do
		collection do
			post  :pay
		end
	end


	root 'welcome#index'
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

	def index
	  @articles = Article.all
	end

	def show
	  @article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
	  @article = Article.find(params[:id])
	end

	def create
	  @article = Article.new(article_params)

	  if @article.save
	    redirect_to @article
	  else
	    render 'new'
	  end
	end

	def update
	  @article = Article.find(params[:id])

	  if @article.update(article_params)
	    redirect_to @article
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @article = Article.find(params[:id])
	  @article.destroy

	  redirect_to articles_path
	end

	private
	  def article_params
	    params.require(:article).permit(:title, :text)
	  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
	 <%= tinymce %>
    <%= f.label :text %><br>
    <%= f.text_area :text, class: "tinymce", :rows => 20 %>
  </p>

  <p class=" col-xs-2">
    <%= f.submit class: "list-group-item text-center" %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
<div class="article">
	<%= render 'form' %>
</div>
<p class="col-xs-2">
	<%= link_to 'Back', articles_path, :class => "list-group-item text-center"  %>
</p>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<table>
	<tr>
		<th>Title</th>
	    <th>Text</th>
	    <th colspan="3">Action</th>
	</tr>

	<% @articles.each do |article| %>
	<tr>
	    <td><%= article.title %></td>
	    <td><%= article.text.html_safe %></td>
	    <td><%= link_to 'Show', article %></td>
	    <td><%= link_to 'Edit', edit_article_path(article) %></td>
	    <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>
	<% end %>
</table>
<br>
<%= link_to 'New article', new_article_path, :class => "list-group-item col-xs-push-5 col-xs-2 text-center" %>
<%= link_to 'Pay', new_payment_path, :class => "list-group-item col-xs-push-5 col-xs-2 text-center" %>
<%= link_to 'Pay Show', payments_path, :class => "list-group-item col-xs-push-5 col-xs-2 text-center" %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<div class="article">
	<%= render 'form' %>
</div>
<%= link_to 'Back', articles_path, :class => "list-group-item text-center col-xs-2" %>

app/views/articles/show.html.erb
<p>
	<!--<strong>Title:</strong>-->
	<h1><%= @article.title %></h1>
</p>

<p>
	<!--<strong>Text:</strong>-->
	<%= @article.text.html_safe %> <!--html_safe = compiler tag html-->
</p>
<br>
<div class="col-xs-2">
	<%= link_to 'Edit', edit_article_path(@article), :class => "list-group-item text-center" %>
</div>
<div class="col-xs-2">
	<%= link_to 'Back', articles_path, :class => "list-group-item text-center" %>
</div>

<div class="comm">
	<h4>Add a comment:</h4>
	<div id="comment-form"><%= render 'comments/form' %></div>
	<p>&nbsp;</p>
	<p>&nbsp;</p>
	<h4>Comments</h4>
	<div id="comments"><%= render @article.comments %></div>
</div>